// <auto-generated />
using System;
using LMS_Na18.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LMS_Na18.Migrations
{
    [DbContext(typeof(LMS_Na18Context))]
    [Migration("20190226153919_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LMS_Na18.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Name");

                    b.Property<int?>("PersonId");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("LMS_Na18.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseId");

                    b.Property<string>("Description");

                    b.Property<int?>("ModuleId");

                    b.Property<int?>("MyActivityId");

                    b.Property<string>("Name");

                    b.Property<int>("PersonId");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("MyActivityId");

                    b.HasIndex("PersonId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("LMS_Na18.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Name");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("LMS_Na18.Models.MyActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime");

                    b.Property<int>("ModuleId");

                    b.Property<int?>("MyTypesId");

                    b.Property<string>("Name");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("MyTypesId");

                    b.ToTable("MyActivity");
                });

            modelBuilder.Entity("LMS_Na18.Models.MyTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("MyTypes");
                });

            modelBuilder.Entity("LMS_Na18.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("LMS_Na18.Models.Course", b =>
                {
                    b.HasOne("LMS_Na18.Models.Person")
                        .WithMany("Courses")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("LMS_Na18.Models.Document", b =>
                {
                    b.HasOne("LMS_Na18.Models.Course")
                        .WithMany("documents")
                        .HasForeignKey("CourseId");

                    b.HasOne("LMS_Na18.Models.Module")
                        .WithMany("documents")
                        .HasForeignKey("ModuleId");

                    b.HasOne("LMS_Na18.Models.MyActivity")
                        .WithMany("documents")
                        .HasForeignKey("MyActivityId");

                    b.HasOne("LMS_Na18.Models.Person")
                        .WithMany("documents")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LMS_Na18.Models.Module", b =>
                {
                    b.HasOne("LMS_Na18.Models.Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LMS_Na18.Models.MyActivity", b =>
                {
                    b.HasOne("LMS_Na18.Models.Module")
                        .WithMany("MyActivities")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LMS_Na18.Models.MyTypes", "MyTypes")
                        .WithMany()
                        .HasForeignKey("MyTypesId");
                });
#pragma warning restore 612, 618
        }
    }
}
